/**
 * cases.ts — Case-review library for interpretation practice.
 *
 * Each case is generated by the same vector engine (so it stays physiologically
 * consistent with the rest of the app) and is presented WITHOUT its label: the
 * fellow scrolls, measures with calipers, and picks the diagnosis, then gets
 * feedback + the teaching point.
 *
 * NOTE: these are synthesised teaching cases, not real patient tracings. Real
 * PhysioNet records (PTB-XL / MIT-BIH) can be plugged in via the same
 * `EcgCase` shape once their signal data is available.
 */

import type { SinusParams } from './engine';

export interface EcgCase {
  id: string;
  /** The correct interpretation (hidden until answered). */
  diagnosis: string;
  /** Answer choices shown to the fellow (includes the diagnosis). */
  options: string[];
  /** Short teaching explanation revealed after answering. */
  teaching: string;
  /** The findings that clinch it (revealed after answering). */
  keyFindings: string[];
  /** Engine parameters that generate the tracing. */
  params: Partial<SinusParams>;
  /** Difficulty band. */
  tier: 1 | 2;
}

export const CASES: EcgCase[] = [
  {
    id: 'c-nsr',
    diagnosis: 'Normal sinus rhythm',
    options: ['Normal sinus rhythm', 'Sinus tachycardia', 'First-degree AV block', 'Atrial fibrillation'],
    teaching:
      'Rate ~72, regular, a P before every QRS with a constant normal PR (~160 ms), narrow QRS, normal axis. Everything in range.',
    keyFindings: ['P before every QRS', 'PR 120–200 ms', 'QRS < 120 ms', 'Normal axis'],
    params: {},
    tier: 1,
  },
  {
    id: 'c-avb1',
    diagnosis: 'First-degree AV block',
    options: ['First-degree AV block', 'Normal sinus rhythm', 'Mobitz I (Wenckebach)', 'Complete heart block'],
    teaching:
      'Every P conducts, but the PR interval is uniformly prolonged (> 200 ms). No dropped beats — that distinguishes it from second-degree block.',
    keyFindings: ['PR > 200 ms', 'Every P conducts (1:1)', 'Constant PR'],
    params: { prMs: 280 },
    tier: 1,
  },
  {
    id: 'c-rbbb',
    diagnosis: 'Right bundle branch block',
    options: ['Right bundle branch block', 'Left bundle branch block', 'Left ventricular hypertrophy', 'Normal'],
    teaching:
      "Wide QRS (≥120 ms) with rSR′ ('rabbit ears') in V1 and a wide slurred S wave in I and V6. Initial forces are normal.",
    keyFindings: ['QRS ≥ 120 ms', 'rSR′ in V1', 'Wide S in I and V6'],
    params: { conductionBlock: 'RBBB' },
    tier: 2,
  },
  {
    id: 'c-lbbb',
    diagnosis: 'Left bundle branch block',
    options: ['Left bundle branch block', 'Right bundle branch block', 'Hyperkalaemia', 'Ventricular tachycardia'],
    teaching:
      'Wide QRS with a broad monophasic (often notched) R in I/aVL/V6, QS or rS in V1, and discordant ST/T. The usual STEMI rules change — think Sgarbossa.',
    keyFindings: ['QRS ≥ 120 ms', 'Broad R in V6 (no q)', 'QS in V1', 'Discordant T'],
    params: { conductionBlock: 'LBBB' },
    tier: 2,
  },
  {
    id: 'c-lafb',
    diagnosis: 'Left anterior fascicular block',
    options: ['Left anterior fascicular block', 'Left posterior fascicular block', 'Inferior MI', 'Normal axis'],
    teaching:
      'Marked left axis deviation (~ −45° to −60°) with qR in I/aVL and rS in the inferior leads, only mildly widened QRS.',
    keyFindings: ['Left axis deviation', 'qR in I/aVL', 'rS in II/III/aVF'],
    params: { conductionBlock: 'LAFB' },
    tier: 2,
  },
  {
    id: 'c-wpw',
    diagnosis: 'Pre-excitation (WPW)',
    options: ['Pre-excitation (WPW)', 'First-degree AV block', 'Right bundle branch block', 'Normal'],
    teaching:
      'Short PR (< 120 ms) with a slurred delta wave at the start of a widened QRS — an accessory pathway pre-exciting the ventricle.',
    keyFindings: ['Short PR (< 120 ms)', 'Delta wave', 'Wide QRS (fusion)'],
    params: { preExcitation: 0.85 },
    tier: 2,
  },
  {
    id: 'c-stemi-inf',
    diagnosis: 'Inferior STEMI',
    options: ['Inferior STEMI', 'Anterior STEMI', 'Pericarditis', 'Normal'],
    teaching:
      'ST elevation in II, III and aVF with reciprocal ST depression in aVL (and I). Inferior wall — usually the RCA.',
    keyFindings: ['ST↑ in II, III, aVF', 'Reciprocal ST↓ in aVL', 'Localises to the inferior wall'],
    params: { stemi: 'inferior' },
    tier: 2,
  },
  {
    id: 'c-stemi-ant',
    diagnosis: 'Anterior STEMI',
    options: ['Anterior STEMI', 'Inferior STEMI', 'Left ventricular hypertrophy', 'Early repolarisation'],
    teaching:
      'ST elevation across the precordial leads (V2–V4). A LAD occlusion — the injury vector points anteriorly onto the chest leads.',
    keyFindings: ['ST↑ in V2–V4', 'Precordial localisation', 'LAD territory'],
    params: { stemi: 'anterior' },
    tier: 2,
  },
  {
    id: 'c-hyperk',
    diagnosis: 'Hyperkalaemia',
    options: ['Hyperkalaemia', 'Anterior STEMI', 'Hypokalaemia', 'Normal'],
    teaching:
      'Tall, peaked, narrow T waves with a flattening P and a widening QRS — the classic progression of rising potassium.',
    keyFindings: ['Tall peaked T waves', 'Flat/absent P', 'Widening QRS'],
    params: { potassiumMmol: 7.5 },
    tier: 2,
  },
  {
    id: 'c-lvh',
    diagnosis: 'Left ventricular hypertrophy',
    options: ['Left ventricular hypertrophy', 'Left bundle branch block', 'Right ventricular hypertrophy', 'Normal'],
    teaching:
      'High QRS voltage — Sokolow-Lyon (S in V1 + R in V5/6) ≥ 3.5 mV — with a leftward axis and lateral T-wave strain.',
    keyFindings: ['Sokolow-Lyon ≥ 3.5 mV', 'Left axis', 'Lateral strain (T inversion)'],
    params: { lvh: 0.9, lvStrain: true },
    tier: 2,
  },
];
